#!/bin/bash
cd "${BASH_SOURCE%/*}" || exit
cd .. || exit

while read p; do
  export $p
done < .build_scripts/variables

yum install -y mariadb-server mariadb epel-release node
sed -i "s/\[mysqld\]/\[mysqld\]\\nport=$ADMIN_DB_PORT/" /etc/my.cnf
systemctl start mariadb

mysqladmin -u $ADMIN_DB_USERNAME password $ADMIN_DB_PASSWORD

npm install
/npm_modules/webpack/bin/webpack.js -p
node server/setup.js -y
node server/index.js
