ALTER TABLE users ADD `instance` int NOT NULL;
UPDATE users SET instance = 1;
ALTER TABLE notificationList ADD `instance` int NOT NULL;
UPDATE notificationList SET instance = 1;
ALTER TABLE meals ADD `instance` int NOT NULL;
UPDATE meals SET instance = 1;
ALTER TABLE signups ADD `instance` int NOT NULL;
UPDATE signups SET instance = 1;
ALTER TABLE datefinder ADD `instance` int NOT NULL;
UPDATE datefinder SET instance = 1;
ALTER TABLE transactions ADD `instance` int NOT NULL;
UPDATE transactions SET instance = 1;
CREATE TABLE IF NOT EXISTS instances ( id int NOT NULL AUTO_INCREMENT, name varchar(150) NOT NULL, company varchar(150), subdomain varchar(150) NOT NULL, address varchar(150) NOT NULL, lang varchar(150) DEFAULT "de-DE", title varchar(150), gmail_user varchar(150), gmail_pass varchar(150), icon varchar(150) DEFAULT "fa-calendar", PRIMARY KEY (id), UNIQUE KEY subdomain (subdomain) );
